highlighter: rouge
safe: true
lsi: false
permalink: "/:title/"

kramdown:
    input: GFM
    hard_wrap: false

lsi: false

future: false

excerpt_separator: <!--more-->

include:
  - .well-known

defaults:
    -
        scope:
            path: ""    # empty string for all files
            type: posts # limit to posts
        values:
            layout: "post"
